# Generated by Django 4.1.7 on 2023-03-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeorder',
            options={'ordering': ('recipe_type',)},
        ),
    ]
