# Generated by Django 4.1.7 on 2023-03-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_order', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
