# Generated by Django 4.1.7 on 2023-03-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_order', '0004_recipeorder_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeorder',
            name='price',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
